// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HasSourceAt struct {
	Package       *Package `json:"package"`
	Source        *Source  `json:"source"`
	Justification string   `json:"justification"`
}

type HasSourceAtFilter struct {
	Package       *PackageFilter `json:"package"`
	Source        *SourceFilter  `json:"source"`
	Justification *string        `json:"justification"`
}

type HasSourceAtInput struct {
	Justification string `json:"justification"`
}

type Package struct {
	Type       string              `json:"type"`
	Namespaces []*PackageNamespace `json:"namespaces"`
}

type PackageFilter struct {
	Type      *string `json:"type"`
	Namespace *string `json:"namespace"`
	Name      *string `json:"name"`
	Version   *string `json:"version"`
	Subpath   *string `json:"subpath"`
}

type PackageInput struct {
	Type      string  `json:"type"`
	Namespace *string `json:"namespace"`
	Name      string  `json:"name"`
	Version   *string `json:"version"`
	Subpath   *string `json:"subpath"`
}

type PackageName struct {
	Name     string            `json:"name"`
	Versions []*PackageVersion `json:"versions"`
	Source   *Source           `json:"source"`
}

type PackageNamespace struct {
	Namespace string         `json:"namespace"`
	Names     []*PackageName `json:"names"`
}

type PackageVersion struct {
	Version string  `json:"version"`
	Subpath string  `json:"subpath"`
	Source  *Source `json:"source"`
}

type Source struct {
	Type       string             `json:"type"`
	Namespaces []*SourceNamespace `json:"namespaces"`
}

type SourceFilter struct {
	Type      *string `json:"type"`
	Namespace *string `json:"namespace"`
	Name      *string `json:"name"`
	Tag       *string `json:"tag"`
	Commit    *string `json:"commit"`
}

type SourceInput struct {
	Type      string  `json:"type"`
	Namespace string  `json:"namespace"`
	Name      string  `json:"name"`
	Tag       *string `json:"tag"`
	Commit    *string `json:"commit"`
}

type SourceName struct {
	Name    string   `json:"name"`
	Tag     *string  `json:"tag"`
	Commit  *string  `json:"commit"`
	Package *Package `json:"package"`
}

type SourceNamespace struct {
	Namespace string        `json:"namespace"`
	Names     []*SourceName `json:"names"`
}
