package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"
	"layout/server/graphql/generated"
	"layout/server/graphql/model"
)

// IngestPackage is the resolver for the ingestPackage field.
func (r *mutationResolver) IngestPackage(ctx context.Context, input model.PackageInput) (*model.Package, error) {
	return r.Backend.IngestPackage(ctx, input)
}

// IngestSource is the resolver for the ingestSource field.
func (r *mutationResolver) IngestSource(ctx context.Context, input model.SourceInput) (*model.Source, error) {
	return r.Backend.IngestSource(ctx, input)
}

// IngestSourceAt is the resolver for the ingestSourceAt field.
func (r *mutationResolver) IngestSourceAt(ctx context.Context, packageArg model.PackageInput, source model.SourceInput, input model.HasSourceAtInput) (*model.HasSourceAt, error) {
	return r.Backend.IngestSourceAt(ctx, packageArg, source, input)
}

// Packages is the resolver for the packages field.
func (r *queryResolver) Packages(ctx context.Context, filter model.PackageFilter) ([]*model.Package, error) {
	return r.Backend.Packages(ctx, filter)
}

// Sources is the resolver for the sources field.
func (r *queryResolver) Sources(ctx context.Context, filter model.SourceFilter) ([]*model.Source, error) {
	return r.Backend.Sources(ctx, filter)
}

// SourceMap is the resolver for the sourceMap field.
func (r *queryResolver) SourceMap(ctx context.Context, filter model.HasSourceAtFilter) ([]*model.HasSourceAt, error) {
	return r.Backend.SourceMap(ctx, filter)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
